
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "querymind.fullname" . }}-redis
  labels:
    {{- include "querymind.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "querymind.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "querymind.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "querymind.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.master.persistence.size | default "5Gi" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "querymind.fullname" . }}-redis
  labels:
    {{- include "querymind.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "querymind.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
